// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HomeHeader: typeof import('./src/components/Home/HomeHeader.vue')['default']
    HomeLikeList: typeof import('./src/components/Home/HomeLikeList.vue')['default']
    HomeMain: typeof import('./src/components/Home/HomeMain.vue')['default']
    HomeTabs: typeof import('./src/components/Home/HomeTabs.vue')['default']
    HomeWeeklyHotList: typeof import('./src/components/Home/HomeWeeklyHotList.vue')['default']
    HomeWeeklyList: typeof import('./src/components/Home/HomeWeeklyList.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHeader: typeof import('./src/components/Search/SearchHeader.vue')['default']
    SearchMain: typeof import('./src/components/Search/SearchMain.vue')['default']
  }
}
